module.exports = Object.freeze({
	LIMIT_MAX: 20,
	LIMIT_MIN: 5,
	SIMPLYRETSAPI: 'simplyretsAPI',
	GET_LISTINGS_BY_LOCATION: 'getListingsByLocation',
	GET_PROPERTY_FOR_LISTING: 'getPropertyForListing',
	GET_ALL_PROPERTIES: 'getAllProperties',
	GET_LISTING_BY_ID: 'getListingById',
	GET_ALL_LISTINGS: 'getAllListings',
	GET_USERS: 'getUsers',
	LISTINGS: 'listings',
	LISTING: 'listing',
	PROPERTIES: 'properties',
	PROPERTY:  'property',
	LISTINGS_BY_LOCATION: 'listingsByLocation',
	USERS: 'users',
})